spring.datasource.url=jdbc:mysql://mysql:3306/user_management
spring.datasource.username=cabsnow
spring.datasource.password=cabsnow123
app.redis.enabled=true
spring.data.redis.host=redis
spring.mail.enabled=false
